# This should generally unify the crate-logic into one workspace

[workspace]
members = [
    "shared-logic",
    "updateResourcePrices",
    "revenueAnalysis",
]

[profile.release]
lto = true
codegen-units = 1
strip = true
overflow-checks = true # Guarantee safety