org: xostat
app: xostat-lambda-api
service: xostat-lambda-api

provider:
  name: aws
  runtime: python3.8
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    DB_HOST: ${self:custom.${self:provider.stage}.DB_HOST}
    DB_PORT: ${self:custom.${self:provider.stage}.DB_PORT}
    DB_NAME: ${self:custom.${self:provider.stage}.DB_NAME}
    DB_USER: ${self:custom.${self:provider.stage}.DB_USER}
    DB_PASSWORD: ${self:custom.${self:provider.stage}.DB_PASSWORD}
plugins:
  - serverless-offline
custom:
  serverless-offline:
    host: localhost
    port: 3000
  dev:
    DB_HOST: localhost
    DB_PORT: 5432
    DB_NAME: postgres
    DB_USER: dev
    DB_PASSWORD: devpass1
functions:
  uploadMatch:
    handler: controllers/upload.upload_matches
    description: upload a list of matches to xodat
    memorySize: 2048
    timeout: 90
    events:
      - http:
          path: /upload
          method: post
          cors: false
          request:
            schemas:
              application/json:
                schema: ${file(schema/uploadSchema.json)}
                name: UploadModel
                description: "Validation for uploading match"
  getUploadRecords:
    handler: controllers/player.get_upload_records
    events:
      - http:
          path: /player/{id}
          method: get
          cors: true
