name: xostat React Deploy

on:
  push:
    branches:
      "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@main
      - name: npm install, build, test
        working-directory: ./xostat-client
          - run: npm install
          - run: npm run build
          - run: npm test
