name: xostat React Deploy

on:
  push:
    branches:
      "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@main
      - run: npm install express
      - run: npm run build
      - run: npm test

