name: xostat React Deploy

on:
  push:
    branches:
      "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    
    steps:
      - uses: actions/checkout@main
      - name: install
        working-directory: ./xostat-client
        run: npm install
      - name: build
        working-directory: ./xostat-client
        run: npm run build
      - name: test
        working-directory: ./xostat-client
        run: npm test
